version: "3.8"

services:    
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8000:80"
    restart: on-failure
    networks:
      - mi-salta-network

networks:
  mi-salta-network:
    external: true
