version: "3.8"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    restart: always
    
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: on-failure
