version: "3.8"

services:    
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8000:80"
    environment:
      - TOKEN_SECRET=98f121bd813d43594f7ec65d73d89086779d304af0a9e76b0b5c79ca29773767
    restart: on-failure
    networks:
      - mi-salta-network

networks:
  mi-salta-network:
    external: true
