version: "3.8"

services:    
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8000:80"
    environment:
      - TOKEN_SECRET=19fd66f305576ede5d55d2c66a329f634a9a2de52063116c3df2263d8ad8907f
    restart: on-failure
    networks:
      - mi-salta-network

networks:
  mi-salta-network:
    external: true
